use_frameworks!

platform :ios, '8.0'

target 'StringTools_Example' do
  pod 'StringTools', :path => '../'

  target 'StringTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
